In the console, type clear and hit Enter or Return. 

This will clear the console output. 

Run the file once while the tasks are longer. 

Copy and paste the terminal results (when task_duration is 3) here.

Microsoft Windows [Version 10.0.22000.1455]
(c) Microsoft Corporation. All rights reserved.

C:\Users\dec99\OneDrive\Documents\44-671\671-mod2>C:/Users/dec99/miniconda3/Scripts/activate.bat

(base) C:\Users\dec99\OneDrive\Documents\44-671\671-mod2>C:/Users/dec99/miniconda3/python.exe c:/Users/dec99/OneDrive/Documents/44-671/671-mod2/multiple_processes.py



STARTING UP.............................
It's 2023-01-23 at 06:22 PM

This file is running on:    nt Windows 10
The Python version is:      3.9.12

The Python interpreter is at:
 C:\Users\dec99\miniconda3\python.exe


DELETED tabble pets.
CREATED table pets.

P2 getting ready to insert Cooper the Rabbit.
P1 getting ready to insert Ace the Dog.
P3 getting ready to insert Emma the Rabbit.
P2 ADDED Cooper the Rabbit.
P2 getting ready to insert Dufus the Dog.
P2 ADDED Dufus the Dog.
Process Process-3:
Traceback (most recent call last):
  File "C:\Users\dec99\miniconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\dec99\miniconda3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\dec99\OneDrive\Documents\44-671\671-mod2\multiple_processes.py", line 110, in process_three
    insert_pet("P3","Emma", "Rabbit")
  File "c:\Users\dec99\OneDrive\Documents\44-671\671-mod2\multiple_processes.py", line 95, in insert_pet
    cur.execute(sql)
sqlite3.OperationalError: database is locked
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\dec99\miniconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\dec99\miniconda3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\dec99\OneDrive\Documents\44-671\671-mod2\multiple_processes.py", line 102, in process_one
    insert_pet("P1","Ace", "Dog")
  File "c:\Users\dec99\OneDrive\Documents\44-671\671-mod2\multiple_processes.py", line 95, in insert_pet
    cur.execute(sql)
sqlite3.OperationalError: database is locked

(base) C:\Users\dec99\OneDrive\Documents\44-671\671-mod2>